name: Release UI package
on:
  push:
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}


    - name: Install dependencies
      run: npm ci

    - name: Init Git User
      run: 
        git config --global user.name "tigawanna"
        git config --global user.email "denniskinuthiaw@gmail.com"
      
    - name: Setup npmrc
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN


    - name: Build and Release UI
      run: npm run build

    - name: Relaese it
      run: npm run release --ci
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
    

